title: Manuel Arevalo
email: m.arevalo.aragon@gmail.com
description: >-
  Soy un desarrollador web, escritor y creativo. ¡Hagamos algo juntos!
baseurl: ""
url: "https://manuelarevalo.com"
timezone: America/Mexico_City
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

social:
  name: Manuel Arevalo
  links:
    - https://github.com/marea
    - https://manuelarevalo.com/twtxt.txt

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
